apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web-app
  template:
    metadata:
      labels:
        app: simple-web-app
    spec:
      containers:
      - name: microservice-lecture1
        image: serghexen/microservice-lecture1:1.0
        ports:
        - name: web
          containerPort: 8000